# Generated by Django 5.0.4 on 2024-04-05 23:20

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_to_do_list_app', '0002_rename_descripton_todolist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title'),
        ),
    ]
