# Generated by Django 5.0.4 on 2024-04-06 00:45

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_to_do_list_app', '0003_todolist_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'verbose_name': 'To Do Task', 'verbose_name_plural': 'To Do List'},
        ),
        migrations.AlterField(
            model_name='todolist',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
